name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # If you have a build step, add it here.
      # - name: Build site
      #   run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Change if your site is in another directory
          cname: 'init_am/init65.co.in'  # Your custom domain
          # Optional: keep files from previous deployment, etc.
